#how to select db to work on that particular db
USE HR;

#ROLL BACK IS USED TO RETRIVE DATA DELETD DATA

#TO CREATE DB
CREATE DATABASE ONLINE_SHOPPING;

USE ONLINE_SHOPPING;

# TO CREATE TABLE IN DB
CREATE TABLE PRODUCTS (
PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(25),
PRICE INT
);

#SELECT FOR SEE TABLE STRICTURE
SELECT * FROM PRODUCTS;

#INSERT VALUES INTO TABLES
INSERT INTO PRODUCTS
(PRODUCT_ID, PRODUCT_NAME, PRICE)
VALUES (12, 'KURTHAS', 200), (13, 'SHIRTS', 300), (14, 'JEANS', 500), (14, 'TANK TOPS', 150);

SELECT * FROM PRODUCTS;

CREATE TABLE CATEGORY(
CATEGORY_ID INT,
CATEGORY_TYPE VARCHAR(20), 
PRODUCT_ID int
);

INSERT INTO CATEGORY
VALUES (1, 'CLOTHING', 12), (2, 'ELECTRONICS', 15), (3, 'MACHINERY', 20);

SELECT * FROM CATEGORY;

USE ONLINE_SHOPPING;
DELETE FROM CATEGORY WHERE PRODUCT_ID = 20;

#DDL COMMANDS (DATA DEFINATION LANGUAGE) THESE COMMANDA USED TO CREATE DATA STRUCTURE FOR DATABASE OR TABLES
#CREATE, DROP, ALTER, TRUNCATE.

#CONSTRAINTS
#SPECIFIC RULE TO FIX ENTRIES IN THE TABLE
#THERE ARE 8 CONSTARINTS 
#1.DATA TYPE CONSTRAINTS 
#2.NULL VALUE CONSTRAINST
#3.PRIMARY KEY 
#4.FOREIGN KEY
#5.DEFAULT CONSTRAINTS
#6.UNIQUE CONSTRAINTS
#7.CHECK CONSTARINTS
#8.AUTO INCREMENT CONSTARINTS

#CREATE A DATBASE BY USING CONSTRAINTS
DROP DATABASE ONLINE_SHOPPING;

CREATE DATABASE ONLINE_SHOPPING;

USE ONLINE_SHOPPING;

#PRIMARY KEYS COLUMN CONTAINS UNIQUE AND NOT NULL VALUES AND ANY TABLES WE HAVE ONLY ONE PRIMARY KEY
CREATE TABLE CATEGORIES(
CATEGORY_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
CATEGORY_NAME VARCHAR(20) NOT NULL UNIQUE,
BRAND_NAME VARCHAR(20) NOT NULL
);

SELECT * FROM CATEGORIES;

INSERT INTO CATEGORIES (CATEGORY_NAME, BRAND_NAME)
VALUES('CLOTHS', 'MYNTRA'), ('ELECTRONICS', 'SONY'), ('MACHINERY', 'PHILIPS'), ('FURNITUE', 'WOOD WORKS'), ('STATIONARY', 'RAYNOLDS');

SELECT * FROM CATEGORIES;

INSERT INTO CATEGORIES (CATEGORY_NAME, BRAND_NAME)
VALUES ('CLOTHS', 'VISUDH');

INSERT INTO CATEGORIES (CATEGORY_NAME, BRAND_NAME)
VALUES (NULL, 'VISUDH');

CREATE TABLE PRODUCTS(
PRODUCT_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(20) NOT NULL,
BRAND_NAME VARCHAR(20) DEFAULT 'NO BRAND', 
PRICE DECIMAL(6, 2) CHECK (PRICE>100.00),
CATEGORY_ID INT UNSIGNED,
FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

INSERT INTO PRODUCTS(PRODUCT_NAME, BRAND_NAME, PRICE, CATEGORY_ID)
VALUES('KURTHA', 'TOKYO TALKIES', 150.20, 1), ('SHIRT', 'RAYMOND', 350.00, 1), ('T.V', 'PHILIPS', 1000.00, 2), ('GENRATOR','OTTIS', 1000.00, 3), 
('BOOK', 'CLASSMATE', 101.00, 5), ('SOFA', 'GREENPLY', 1000.00, 4); 

INSERT INTO PRODUCTS( PRODUCT_NAME, CATEGORY_ID)
VALUES('LAPTOP', 2);

SELECT * FROM PRODUCTS;
DELETE FROM PRODUCTS WHERE CATEGORY_ID=1;

TRUNCATE PRODUCTS;

DROP TABLE PRODUCTS;
SELECT * FROM CATEGORIES;
ALTER TABLE CATEGORIES ADD COLUMN COUNTRY_NAME VARCHAR(10);

UPDATE CATEGORIES SET COUNTRY_NAME= 'USA';
UPDATE CATEGORIES SET COUNTRY_NAME= 'UK' WHERE CATEGORY_ID=4;
UPDATE CATEGORIES SET COUNTRY_NAME= 'EUROPE' WHERE CATEGORY_ID=2;

ALTER TABLE CATEGORIES RENAME COLUMN BRAND_NAME TO COMPANY_NAME;

