#DML COMMANDS (DATA MANUPULATION LAUNGAGE
#SELECT, UPDATE, INSERT, DELETE, 

USE HR;
SELECT * FROM EMPLOYEES;
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES;
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES;

SELECT FIRST_NAME FROM EMPLOYEES 
ORDER BY FIRST_NAME DESC;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY>10000;

SELECT DISTINCT COUNT(FIRST_NAME) FROM EMPLOYEES;

SELECT (HIRE_DATE) FROM EMPLOYEES
WHERE HIRE_DATE> '1996-05-08';

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE SALARY<6000;

SELECT SUM(SALARY), DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%N';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%O%';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME NOT LIKE '%O%';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%' OR FIRST_NAME LIKE 'E%' OR FIRST_NAME LIKE 'I%' OR FIRST_NAME LIKE 'O%' OR FIRST_NAME LIKE 'U%';

SELECT PHONE_NUMBER FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '______3%';

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT* FROM EMPLOYEES;
SELECT ROUND(AVG (SALARY),2), DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

