use pizza;
SELECT * FROM PIZZA_SALES;
DESC PIZZA_SALES;

#1. FIND TOTAL NO OF PIZZA IDS FROM PIZZA SALES
SELECT COUNT(PIZZA_ID) FROM PIZZA_SALES;

#2.FIND ORDERS FROM PIZZA SALES
SELECT COUNT(ORDER_ID) FROM PIZZA_SALES;

#3. HOW MANY UNIQUE ORDERS ARE PLACED
SELECT COUNT(DISTINCT ORDER_ID) FROM PIZZA_SALES;

#4. HOW MANY QUANTITIES FROM PIZZA_SALES
SELECT COUNT(QUANTITY) FROM PIZZA_SALES;

#5, HOW MANY UNIQUE QUQNTITIES PLACED IN PIZZA SALES
SELECT DISTINCT QUANTITY AS QUANITY, COUNT(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY QUANTITY;

#6. HOW MANY UNIQUE ORDER DATE PRESENT IN PIZZA_SALES
SELECT DISTINCT ORDER_DATE, COUNT(ORDER_DATE) FROM PIZZA_SALES
GROUP BY ORDER_DATE;

#7. HOW MANY UNIQUE ORDER TIME PRESENT IN PIZZA_SALES
SELECT DISTINCT ORDER_TIME FROM PIZZA_SALES;

#8. What is the Maximum and minimum quantities ordered?
SELECT MIN(QUANTITY), MAX(QUANTITY) FROM PIZZA_SALES;

#9. What is the Count of the number of unique quantity ordered by sum of Quantity?
SELECT DISTINCT QUANTITY, SUM(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY QUANTITY;

#10 What are the different pizza names?
SELECT DISTINCT PIZZA_NAME FROM PIZZA_SALES;

#11. What is the total quantity of different names of pizzas ordered?
SELECT DISTINCT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_PIZZAS FROM PIZZA_SALES
GROUP BY PIZZA_NAME;

#12. Name top 10 pizza names which people loves the most?
SELECT DISTINCT PIZZA_NAME_ID, SUM(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY PIZZA_NAME_ID
ORDER BY TOTAL_QUANTITY DESC 
LIMIT 10;

#13.Name the pizza which people ordered vey less time?
SELECT DISTINCT PIZZA_NAME_ID, SUM(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY PIZZA_NAME_ID
ORDER BY TOTAL_QUANTITY ASC
LIMIT 1;

#14. Calculate per order quantity?
SELECT SUM(QUANTITY)/COUNT(DISTINCT ORDER_ID) FROM PIZZA_SALES;

#15. Find the dates from which we have records for pizza sales?
SELECT MAX(ORDER_DATE), MIN(ORDER_DATE) FROM PIZZA_SALES;

#16.On which date maximum quantities of pizza ordered?
SELECT SUM(QUANTITY) AS MAX_SALES, ORDER_DATE FROM PIZZA_SALES
GROUP BY ORDER_DATE  #CATEGORICAL COLUMN
ORDER BY MAX_SALES DESC LIMIT 1; #AGGREGATE FUNC CONTINOUS NUMERIC

#17. On which date minimum quantities of pizza ordered?
SELECT SUM(QUANTITY) AS MIN_SALES, ORDER_DATE FROM PIZZA_SALES
GROUP BY ORDER_DATE
ORDER BY MIN_SALES ASC LIMIT 1;

#18. On which date maximum orders placed?
SELECT COUNT(ORDER_ID) AS MAX_ORDERS, ORDER_DATE FROM PIZZA_SALES
GROUP BY ORDER_DATE
ORDER BY MAX_ORDERS DESC LIMIT 1;

#19. On which date minimum orders placed?
SELECT COUNT(ORDER_ID) AS MIN_ORDER, ORDER_DATE FROM PIZZA_SALES
GROUP BY ORDER_DATE
ORDER BY MIN_ORDER ASC LIMIT 1;

#20. Busiest time slot for pizza store?
SELECT CASE WHEN TIME(ORDER_TIME) BETWEEN '09:00:00' AND '12:00:00' THEN 'MORNING'
	 WHEN TIME(ORDER_TIME) BETWEEN '12:00:00' AND '16:00:00' THEN 'AFTERNOON'
     WHEN TIME(ORDER_TIME) BETWEEN '16:00:00' AND '20:00:00' THEN 'EVENING'
     WHEN TIME(ORDER_TIME) BETWEEN '20:00:00' AND '23:59:59' THEN 'LATE NIGHT'
     END ORDER_TIME_ZONE, SUM(QUANTITY) FROM PIZZA_SALES
	 GROUP BY ORDER_TIME_ZONE
     ORDER BY SUM(QUANTITY) DESC LIMIT 1;

#21. What is maximum and minimum pizza price?
SELECT MAX(UNIT_PRICE), MIN(UNIT_PRICE) FROM PIZZA_SALES;

#22.Calculate average pizza price?
SELECT ROUND(AVG(UNIT_PRICE),2) FROM PIZZA_SALES;

#23.Which pizza is more affordable?
SELECT MIN(UNIT_PRICE) AS PRICE, PIZZA_NAME FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY PRICE ASC LIMIT 1;

#24.Show me that order id which spend most for buying pizzas?
SELECT DISTINCT ORDER_ID, SUM(TOTAL_PRICE) FROM PIZZA_SALES
GROUP BY ORDER_ID
ORDER BY SUM(TOTAL_PRICE) DESC LIMIT 1;

#25.Show me that order id which spend LEAST for buying pizzas?
SELECT DISTINCT ORDER_ID, SUM(TOTAL_PRICE) FROM PIZZA_SALES
GROUP BY ORDER_ID
ORDER BY SUM(TOTAL_PRICE) ASC LIMIT 1;
#ANS 112	9.75

#26.How many quantities ordered for each pizza size?
SELECT PIZZA_SIZE, SUM(QUANTITY) FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

#27.Number of total orders placed for each pizza size?
SELECT PIZZA_SIZE, COUNT(ORDER_ID) FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

#28.Name the pizza name in pizza size which is affordable?
SELECT DISTINCT PIZZA_SIZE, PIZZA_NAME, MIN(UNIT_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_NAME, PIZZA_SIZE
ORDER BY MIN(UNIT_PRICE) ASC LIMIT 5;

#29.FIND PIZZA CATEGORIES BY ORDER ID
SELECT PIZZA_CATEGORY, ORDER_ID FROM PIZZA_SALES;

#30.For which pizza category most orders are placed? Return all pizza categories by pizza orders by descresing order.
SELECT PIZZA_CATEGORY, COUNT(ORDER_ID) FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY
ORDER BY COUNT(ORDER_ID) DESC;

#31. Find out Number of quantities ordered for each category of pizza?
SELECT PIZZA_CATEGORY, SUM(QUANTITY) FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

#FIND OUT HOW MANY PIZZA SOLD BY PIZZA SIZE AND PIZZA CATEGORY?
SELECT PIZZA_CATEGORY, PIZZA_SIZE, SUM(QUANTITY) FROM PIZZA_SALES
GROUP BY PIZZA_SIZE, PIZZA_CATEGORY;

# 29. Calculate average, max, min unit pizza price for each pizza size?
SELECT PIZZA_SIZE, ROUND(AVG(UNIT_PRICE),2), MAX(UNIT_PRICE), MIN(UNIT_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

# 30. Calculate average, max, min total price for each pizza size?
SELECT PIZZA_SIZE, ROUND(AVG(TOTAL_PRICE),2), MAX(TOTAL_PRICE), MIN(TOTAL_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

# 31. Calculate average, max, min unit pizza price for each pizza category?
SELECT PIZZA_CATEGORY, ROUND(AVG(UNIT_PRICE),2), MAX(UNIT_PRICE), MIN(UNIT_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

# 31. Calculate average, max, min total price for each pizza category?
SELECT PIZZA_CATEGORY, ROUND(AVG(TOTAL_PRICE),2), MAX(TOTAL_PRICE), MIN(TOTAL_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

# 33. What are the DIFFERENT pizzas are available?
SELECT DISTINCT PIZZA_NAME FROM PIZZA_SALES;

# 34. Find out Pizzas by total quantities ordered?
SELECT PIZZA_NAME, SUM(QUANTITY) FROM PIZZA_SALES
GROUP BY PIZZA_NAME;

# 35. Name top 10 pizzas which people loves to buy?
SELECT PIZZA_NAME, SUM(QUANTITY) FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY SUM(QUANTITY) DESC LIMIT 10;

# 36. Name the pizza which people ordered vey less time?
SELECT PIZZA_NAME, SUM(QUANTITY) FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY SUM(QUANTITY) ASC LIMIT 1;

# 37. Change Pizza size if "S" then "Small" etc.
SELECT DISTINCT PIZZA_SIZE FROM PIZZA_SALES;
SELECT DISTINCT PIZZA_SIZE,
CASE WHEN PIZZA_SIZE= 'S' THEN 'SMALL'
     WHEN PIZZA_SIZE= 'M' THEN 'MEDIUM'
     WHEN PIZZA_SIZE= 'L' THEN 'LARGE'
     WHEN PIZZA_SIZE= 'XL' THEN 'EXTRA LARGE'
     WHEN PIZZA_SIZE= 'XXL' THEN 'DOUBLE EXTRA LARGE'
END PIZZA_SIZE_UPDATED FROM PIZZA_SALES;

SELECT DISTINCT PIZZA_SIZE,
CASE PIZZA_SIZE WHEN 'S' THEN 'SMALL'
                WHEN 'M' THEN 'MEDIUM'
                WHEN'L' THEN 'LARGE'
                WHEN'XL' THEN 'EXTRA LARGE'
                WHEN 'XXL' THEN 'DOUBLE EXTRA LARGE'
END PIZZA_SIZE_UPDATED FROM PIZZA_SALES;




